#include <iostream>
#include <fstream>
#include <set>

#include "TFile.h"
#include "TTree.h"
#include "TMath.h"
#include "TRandom3.h"

#include "Tools/Flux/GSimpleNtpFlux.h"

/*
  Converts neutrino rays generated by target simulation into GSimpleNtpFlux format for GENIE
  see https://github.com/GENIE-MC/Generator/blob/master/src/Tools/Flux/GSimpleNtpFlux.h for details.
*/

int main(int argc, char **argv)
{

   if (argc != 4) {
      std::cout << "Three arguments required: path to target sim file AND output file name AND number of pp collisions used "
                << std::endl;
      return -1;
   }

   std::string inFileName = std::string(argv[1]);
   std::string outFileName = std::string(argv[2]);
   double pot_number = std::stod(argv[3]);

   // To generate a random seed which is stored in the metadata.
   TRandom3 *ran = new TRandom3();

   std::cout << "Start converting" << std::endl;

   // Set up input file
   TFile *inputfile = TFile::Open(inFileName.c_str(), "READ");

   // Input variables
   Float_t x, y, z, px, py, pz;
   Float_t id, pythiaid, parentid;
   Float_t w, ecut;

   TTree *input_tree = (TTree *)inputfile->Get("pythia8-Geant4");
   input_tree->SetBranchAddress("x", &x);
   input_tree->SetBranchAddress("y", &y);
   input_tree->SetBranchAddress("z", &z);

   input_tree->SetBranchAddress("px", &px);
   input_tree->SetBranchAddress("py", &py);
   input_tree->SetBranchAddress("pz", &pz);

   input_tree->SetBranchAddress("id", &id);
   input_tree->SetBranchAddress("pythiaid", &pythiaid);
   input_tree->SetBranchAddress("parentid", &parentid);

   input_tree->SetBranchAddress("w", &w);
   input_tree->SetBranchAddress("ecut", &ecut);

   // Scoring plane info
   // Find a Minimum and Maximum of the x, y, z axis (FLUKA coordinates) cm
   // Max z, min z
   double min_z = 999;
   double max_z = -999;
   // Max x, min x
   double min_x = 999;
   double max_x = -999;
   // Max y, min y
   double min_y = 999;
   double max_y = -999;

   TFile *fOut = new TFile(outFileName.c_str(), "RECREATE");
   TTree *tOut = new TTree("flux", "a simple flux n-tuple");
   TTree *metaOut = new TTree("meta", "metadata for flux n-tuple");

   genie::flux::GSimpleNtpEntry *gsimple_entry = new genie::flux::GSimpleNtpEntry;
   tOut->Branch("entry", &gsimple_entry);
   genie::flux::GSimpleNtpMeta *meta_entry = new genie::flux::GSimpleNtpMeta;
   metaOut->Branch("meta", &meta_entry);

   genie::flux::GSimpleNtpAux *aux_entry = new genie::flux::GSimpleNtpAux;
   tOut->Branch("aux", &aux_entry);

   UInt_t metakey = TString::Hash(outFileName.c_str(), strlen(outFileName.c_str()));
   metakey &= 0x7FFFFFFF;

   // Metadata accumulators:
   std::set<int> pdglist;
   double min_weight = 1e10;
   double max_weight = -1e10;
   double max_energy = 0;


   for (Long64_t i = 0; i < input_tree->GetEntries(); i++) {
      input_tree->GetEntry(i);
      
      gsimple_entry->Reset();
      aux_entry->Reset();
      gsimple_entry->metakey = metakey;

      z = 165.6400; //FOR THIS TESTING FILE, ALL NEUTRINOS ARE GENERATED AT THIS Z, SO WE CAN SET IT TO A FIXED VALUE. IN FUTURE, THIS SHOULD BE TAKEN FROM THE FILE.

      min_z = TMath::Min(min_z, z);
      max_z = TMath::Max(max_z, z);
      min_x = TMath::Min(min_x, x);
      max_x = TMath::Max(max_x, x);
      min_y = TMath::Min(min_y, y);
      max_y = TMath::Max(max_y, y);


      gsimple_entry->pdg = id;
      gsimple_entry->wgt = w;
      gsimple_entry->vtxx = x * 1 / 100; // in m
      gsimple_entry->vtxy = y * 1 / 100;
      gsimple_entry->vtxz = z * 1 / 100;
      gsimple_entry->dist = 0.; // Distance from hadron decay point to neutrino "vertex", to use for oscillations,
                                      // for example. Don't use.
      gsimple_entry->px = px; // in GeV/c
      gsimple_entry->py = py;
      gsimple_entry->pz = pz;
      //massless neutrinos
      gsimple_entry->E = TMath::Sqrt(px*px + py*py + pz*pz);

      // Set auxiliary data
      aux_entry->auxint.push_back(parentid);
      aux_entry->auxint.push_back(pythiaid);
      aux_entry->auxint.push_back(ecut);


      // Accumulate metadata
      pdglist.insert(gsimple_entry->pdg);
      min_weight = TMath::Min(min_weight, gsimple_entry->wgt);
      max_weight = TMath::Max(max_weight, gsimple_entry->wgt);
      max_energy = TMath::Max(max_energy, gsimple_entry->E);

      // All done!
      tOut->Fill();
   }
   

   // plane corner and plane direction of the scoring plane (The scoring plane is tilted)
   double plane_corner[] = {min_x, min_y, min_z};
   double plane_dir1[] = {max_x - min_x, 0, max_z - min_z};
   double plane_dir2[] = {0, max_y - min_y, max_z - min_z};

   // Sort out metadata
   // Copy pdg list
   meta_entry->pdglist.clear();
   for (std::set<int>::const_iterator pdg_iterator = pdglist.begin(); pdg_iterator != pdglist.end(); ++pdg_iterator)
      meta_entry->pdglist.push_back(*pdg_iterator);
   meta_entry->maxEnergy = max_energy;
   meta_entry->maxWgt = max_weight;
   meta_entry->minWgt = min_weight;

   meta_entry->protons = pot_number; // Number of protons on target.
   for (int i = 0; i < 3; i++)
      meta_entry->windowBase[i] = plane_corner[i] * 1 / 100;
   for (int i = 0; i < 3; i++)
      meta_entry->windowDir1[i] = plane_dir1[i] * 1 / 100;
   for (int i = 0; i < 3; i++)
      meta_entry->windowDir2[i] = plane_dir2[i] * 1 / 100;

   meta_entry->infiles.push_back(inFileName);
   meta_entry->seed = ran->GetSeed();
   meta_entry->metakey = metakey;

   meta_entry->auxintname.push_back("parentid");
   meta_entry->auxintname.push_back("pythiaid");
   meta_entry->auxintname.push_back("ecut");

   metaOut->Fill();

   fOut->cd();
   metaOut->Write();
   tOut->Write();
   fOut->Close();
   std::cout << "Done converting" << std::endl;
}
